apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: leidne42t-python 
  janus-idp.io/tekton: leidne42t-python
  backstage.io/kubernetes-id: leidne42t-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: leidne42t-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  