apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: leidne42t-python
  janus-idp.io/tekton: leidne42t-python
  backstage.io/kubernetes-id: leidne42t-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: leidne42t-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
